### ISSUE TITLE
Algorithms Project

### ISSUE THREAD

**Issue by Jomarm92x** [cop1000/cop1000#162]
Unable to edit pull requests, maybe in the wrong group or team.

**Comment by Javier-of-the-Rich-Port** [comment]
I'm having the same issue I can add reactions and new Pull request all together but not edit existing ones

**Comment by hectorsector** [comment]
@Jomarm92x you're not in any group or team at the moment. I can tell because there's no badge next to your name. See how @Javier-of-the-Rich-Port has a badge that says he's a member? Anyway, this is driven from the very first week or two of class when an assignment had you tell me your GitHub username. You should have an email invitation from a few months ago, but if you can't find it, try following [these instructions](https://github.com/cop1000/cop1000/issues/157#issuecomment-257919559) and it should get you what you're looking for.

**Comment by hectorsector** [comment]
@Javier-of-the-Rich-Port your issue may be different as you've already got the badge. Can you capture your screen and show me what happens when you try to edit? A couple of tips:
- make sure you're using Chrome or Firefox (or Safari on a Mac)
- to record your screen, you can use [LiceCap](http://www.cockos.com/licecap) to save your recording as a GIF.

**Comment by hectorsector** [comment]
It seems that this issue is resolved at least for @Jomarm92x. If you're still having issues, @Javier-of-the-Rich-Port, please reopen this issue or create a new one.
