### ISSUE TITLE
Jay Aponte

### ISSUE THREAD

**Issue by gaponte6** [cop1000/cop1000#53]
Hi Class, my name is Gerardo Aponte Jr., but Id like to be called Jay. I Like hanging out with friends, playing video games and watching anime. Im interested in this class because I want to know more about programming and get a degree in computer science. I want to learn the behind the scenes of programming a video game. I have we have a quick semester, have fun!

![picture](https://cloud.githubusercontent.com/assets/21376492/18154526/6fe9ead6-6fd3-11e6-9192-db88545ea17b.png)

**Comment by hectorsector** [comment]
Welcome, @gaponte6. What kind of games do you like? Console or PC?

**Comment by Nathan801** [comment]
Hello Gerardo, It's good to know someone else will be fighting the temptation to play games this semester. About a year and a half ago i finally built my own PC for the first time and haven't gone back to consoles since. The gaming industry is highly competitive, but if you want it bad enough you can go as far as you want to. It took me a little too long to actually believe that myself. I wish you the absolute best this semester and beyond.

**Comment by dmattingley1** [comment]
Hey Gerardo! Who would've thought that a programming course would be full of gamers, I'm glad I'll be able to learn alongside so many people of similar interest. Good luck with your studies.

**Comment by hectorsector** [comment]
Great work @gaponte6! :+1: :tada: I am closing this issue because I've now graded this assignment and your grade has been updated on Blackboard. Please ensure you're looking there to verify your grade is correct.
